# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [66]:
import numpy as np 

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jobymacbookpro/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jobymacbookpro/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jobymacbookpro/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jobymacbookpro/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jobymacbookpro/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jobymacbookpro/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jobymacbookpro/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jobymacbookpro/opt/anaconda3/inc

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [12]:
print("The memory sixe of x is: ", x.size * x.itemsize, "bytes, and each element is: ",x.itemsize, "bytes")

The memory sixe of x is:  80 bytes, and each element is:  8 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
python -c "import numpy; numpy.info(numpy.add)"

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
y = np.zeros(10)
y[4] = 1 
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [3]:
w = np.arange(10,50)
print(w)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [5]:
w = w[::-1]
print(w)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
z = np.arange(0,9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [2]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [3]:
i = np.eye(3,3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [6]:
ran = np.random.random((3,3,3))
print(ran)

[[[0.32046742 0.54623391 0.31497665]
  [0.65382354 0.34603979 0.79781809]
  [0.69972098 0.91690774 0.49197518]]

 [[0.16602908 0.44440262 0.89204135]
  [0.54143155 0.92084586 0.25132328]
  [0.77619675 0.82345326 0.57336272]]

 [[0.12508339 0.79036181 0.27537171]
  [0.46210636 0.58996217 0.2521003 ]
  [0.11169722 0.16278038 0.70636452]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
ten = np.random.rand(10, 10)
m = ten.max()
mi = ten.min()
print(ten, "\nMax: ", m, "\nMin: ", mi)

[[0.30688538 0.81544582 0.67539944 0.88538278 0.29391364 0.2819358
  0.01673342 0.62237042 0.4406961  0.30279742]
 [0.6040682  0.89334822 0.55143714 0.89073933 0.13605859 0.74591435
  0.02693335 0.45657016 0.09915363 0.46018992]
 [0.75600904 0.61791038 0.9904165  0.33864201 0.72664932 0.4211272
  0.89838939 0.52983772 0.54378829 0.65548428]
 [0.53908307 0.67699806 0.26311613 0.41578143 0.61603297 0.69898894
  0.63038302 0.22876126 0.82408582 0.27404986]
 [0.88837843 0.80505735 0.54907388 0.71082575 0.00575853 0.19684993
  0.93197133 0.22976762 0.01185299 0.90488491]
 [0.16033993 0.35173809 0.71197531 0.00747957 0.4773558  0.18346599
  0.70164711 0.99268793 0.12150778 0.95823467]
 [0.54543358 0.18018732 0.29396547 0.06312121 0.16540469 0.90755183
  0.60028162 0.57827962 0.14684241 0.94264237]
 [0.29190713 0.39142683 0.71127336 0.76228682 0.73364267 0.31762979
  0.03305411 0.50687838 0.12034923 0.58452961]
 [0.65883153 0.26650344 0.88437735 0.03173929 0.73131201 0.51925997
  0.02578208 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
v = np.random.rand(1,30)
mean = v.mean()
print(v, "\n Mean: ", mean)

[[0.66465863 0.07249916 0.7010683  0.55994833 0.44896561 0.27903535
  0.32292079 0.15353379 0.97753832 0.94640832 0.11939811 0.74561699
  0.52065353 0.11556872 0.11278271 0.86711463 0.70662706 0.08642565
  0.44651959 0.23793342 0.06759333 0.5856996  0.88681802 0.9916017
  0.60230414 0.21881671 0.99642253 0.50431244 0.99165286 0.26035505]] 
 Mean:  0.5063597793086246


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [25]:
twoD = np.ones((4,4))
twoD[1:-1, 1:-1] = 0
print(twoD)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [34]:
zer = np.ones((4,4))
print(zer)
zer = np.pad(zer, pad_width=1, mode='constant', constant_values=0)
print("\n",zer)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [4]:
print(0 * np.nan) #nan
print(np.nan == np.nan) 
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [16]:
x = np.arange(1,5)
five = np.diag(x, k=-1)
print(five)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [24]:
ch = np.ones((8,8))
ch[::2, ::2] = 0
ch[1::2, 1::2] = 0
print(ch)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [26]:
index = np.ones((6,7,8))
i = np.unravel_index(99, (6,7,8))
print(i)
#position 4, 6th array, in 2nd array

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [34]:
a = np.array([[0,1],[1,0]])
r = (4,4)
che = np.tile(a, r)
print(che)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [47]:
norm = np.random.random((5,5))
n = (norm - np.mean(norm))/ np.std(norm)
print(norm, "\n")
print(n)

[[0.93209436 0.53675187 0.8004148  0.67828559 0.65892232]
 [0.96388417 0.19712502 0.1043592  0.20149413 0.80785792]
 [0.48412563 0.45933299 0.26920344 0.12148595 0.72581234]
 [0.93983543 0.15218714 0.04968136 0.87291931 0.59369883]
 [0.36678283 0.26079749 0.15097784 0.85421779 0.1130872 ]] 

[[ 1.43073253  0.14603159  1.00282796  0.60595814  0.54303545]
 [ 1.53403636 -0.95761635 -1.2590672  -0.94341854  1.02701506]
 [-0.02498209 -0.10554802 -0.72339105 -1.2034123   0.76040057]
 [ 1.45588781 -1.10364603 -1.43674777  1.23843788  0.33108588]
 [-0.40629805 -0.75070692 -1.10757576  1.17766562 -1.23070478]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [51]:
colour = np.dtype([("R", np.ubyte, 1), ("G", np.ubyte, 1), ("B", np.ubyte, 1), ("A", np.ubyte, 1)])
print(colour)
#just sure I undertsand the warning here 

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


<ipython-input-51-375ef31b1100>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  colour = np.dtype([("R", np.ubyte, 1), ("G", np.ubyte, 1), ("B", np.ubyte, 1), ("A", np.ubyte, 1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [53]:
ar1 = np.random.random((5,3))
ar2 = np.random.random((3,2))
# create a new array which is the product of the previous 2 
mul = np.dot(ar1,ar2)
print(mul)

[[0.2687166  0.29812287]
 [0.87182345 0.98177306]
 [0.74369361 0.99611079]
 [0.4269487  0.42693336]
 [0.57033015 0.47819352]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [58]:
a = np.arange(15)
print(a)
a[(a > 3) & (a < 8)] *= -1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [59]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [60]:
np.array(0) / np.array(0) # zero duivde error 
np.array(0) // np.array(0) # zero divide error
np.array([np.nan]).astype(int).astype(float)

<ipython-input-60-cd809174da5d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-60-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [73]:
# np.ceil() rounds everything up or away from 0 
ex = np.random.random(22)
exr = np.ceil(ex)
print(ex, end="\n")
print(exr)

[0.00548224 0.71235342 0.85716685 0.87248505 0.17433205 0.61277483
 0.85838316 0.416233   0.04595002 0.6335682  0.75663315 0.75227437
 0.60649348 0.32216622 0.14378608 0.38490786 0.01632755 0.01513664
 0.85583608 0.35791611 0.41052166 0.02275658]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [80]:
one = np.random.random(22)
#aaded common values 
one[12] = 7
two = np.random.random(22)
# added comon value
two[12] = 7
com = np.intersect1d(one,two)
# 1 common value
print("List of common values", com)

List of common values [7.]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# np.seterr(all='ignore') will ignore all warnings
# commented out to make sure they stay on and I see them 
# np.seterr(**defaults) to go back to the defaults 

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [84]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) # not true due to invalid value of -1 
# by using np.emath.sqrt(-1) -1 becomes a valid value 
# np.sqrt() cannot have negative values

False


<ipython-input-84-49139eb50aef>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1)) # not true due to invalid value of -1


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [95]:
today = np.datetime64('today', 'D')
yest = np.datetime64('today','D') - np.datetime64(1,'D')
tomm = np.datetime64('today', 'D') - np.datetime64(-1,'D')
print("yesterday ", yest) # I'm not sure why this prints as days and not a date 
print("today ", today)
print("tommorow",  tomm)

yesterday  18602 days
today  2020-12-07
tommorow 18604 days


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [103]:
# 31 days in july 
#use arange and dtype datetime64
days = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
#just for fun 
weeks = np.arange('2016-07', '2016-08', dtype='datetime64[W]')
months = np.arange("2015-01", "2020-12", dtype="datetime64[M]")
print("Days\n", days, end="\n\n")
print("Weeks\n",  weeks, end="\n\n")
print("Months\n",months)

Days
 ['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']

Weeks
 ['2016-06-30' '2016-07-07' '2016-07-14' '2016-07-21']

Months
 ['2015-01' '2015-02' '2015-03' '2015-04' '2015-05' '2015-06' '2015-07'
 '2015-08' '2015-09' '2015-10' '2015-11' '2015-12' '2016-01' '2016-02'
 '2016-03' '2016-04' '2016-05' '2016-06' '2016-07' '2016-08' '2016-09'
 '2016-10' '2016-11' '2016-12' '2017-01' '2017-02' '2017-03' '2017-04'
 '2017-05' '2017-06' '2017-07' '2017-08' '2017-09' '2017-10' '2017-11'
 '2017-12' '2018-01' '2018-02' '2018-03' '2018-04' '2018-05' '2018-06'
 '2018-07' '2018-08' '2018-09' '2018-10' '2018-11' '2018-12' '2019-01'
 '2019-02' '201

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [104]:
# create A and B 
A = np.ones(3)
print(A)
B = np.ones(3)*2 # time 2 to get differnet numbers
print(B)
# do the brackets first 
B = np.add(A,B) # reuse B as a place to stoee the result 
A = np.negative(A)
A = np.divide(A,2) # reuse A as a place to sore the reuslt 
# now multiply them together 
A = np.multiply(A,B)
print(A)

[1. 1. 1.]
[2. 2. 2.]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [115]:
start = np.random.uniform(0,10,10)
print(start)
one = start - start%1
print(one)
two = np.ceil(start)
print(two)
three = np.floor(start)
print(three)
four = np.trunc(start)
print(four)
five = start.astype(int)


[7.91178391 3.92252104 9.79045289 0.44729172 9.26823529 1.8027329
 0.64559877 1.92729745 2.29955874 4.89422134]
[7. 3. 9. 0. 9. 1. 0. 1. 2. 4.]
[ 8.  4. 10.  1. 10.  2.  1.  2.  3.  5.]
[7. 3. 9. 0. 9. 1. 0. 1. 2. 4.]
[7. 3. 9. 0. 9. 1. 0. 1. 2. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [123]:
rows = np.arange(5)
m = np.tile(rows, 5)
ms = np.reshape(m, (5,5))
#m = np.reshape(rows, (5,5))
print(rows)
print(ms)
# better way 
r2 = np.zeros((5,5))
r2 += np.arange(5)
print("\n", r2)

[0 1 2 3 4]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [125]:
def gen_ints():
    for x in range(10):
        yield x 

cv = np.fromiter(gen_ints(), int)
print(cv)


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [140]:
vc = np.linspace(0.1,0.9,10)
print(vc, "with Size ", vc.size)

[0.1        0.18888889 0.27777778 0.36666667 0.45555556 0.54444444
 0.63333333 0.72222222 0.81111111 0.9       ] with Size  10


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [144]:
rvc = np.random.rand(10)
print("unsorted ", rvc)
rvc.sort()
print("sorted ",rvc)

unsorted  [0.92621573 0.59449976 0.63446517 0.47629062 0.60793478 0.68331566
 0.06512106 0.38845926 0.28966019 0.71158071]
sorted  [0.06512106 0.28966019 0.38845926 0.47629062 0.59449976 0.60793478
 0.63446517 0.68331566 0.71158071 0.92621573]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)